RWTH-EBC/TEASER

- teaser/logic/buildingobjects/thermalzone.py
This is just a minor bugfix, as it will only occur if no rooftop is defined
> Change if statement for rooftops

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
This closes #446
It is again the `master`, as templates only get active in the `master`. However, as this does not change the code itself, we do not need to raise the version number
> Adds templates to TEASER

- teaser/logic/archetypebuildings/bmvbs/office.py
This solves #559. It's only an improvement of documentation, now correctly stating that the default for `window_layout` is 0 (not 1). The default value is still 0.
> Issue559 windowlayout

- teaser/data/input/citygml_input.py
- teaser/data/input/teaserxml_input.py
- teaser/logic/archetypebuildings/bmvbs/office.py
- teaser/project.py
- tests/test_data.py
With this implementation, we are now calculating the facade area if the required information is available. Furthermore, we are now using 3 as a default value for the office_layout instead of 0.
#569
> Switch from facade area estimation to calculation

- teaser/logic/buildingobjects/calculation/aixlib.py
For #622: This only increases the version of AixLib used to the current v0.8.1
> Increase AixLib version

- teaser/data/input/inputdata/TypeElements_TABULA_DE.json
- teaser/data/input/inputdata/TypeElements_TABULA_DK.json
This changes default values for shading in Tabula building according to #653 
I just replaced the default values in json. Naming convention should be solved in a new PR
> change shading default

- teaser/logic/archetypebuildings/tabula/de/singlefamilyhouse.py
- teaser/logic/archetypebuildings/tabula/dk/singlefamilyhouse.py
For #662
- Use zone's area instead of the total building area to calculate the correct share of areas for the model for the tabula building archetypes.
> Fix area calculation by using correct base area

- teaser/logic/buildingobjects/buildingphysics/groundfloor.py
- teaser/logic/buildingobjects/buildingphysics/outerwall.py
- teaser/logic/buildingobjects/buildingphysics/rooftop.py
- teaser/logic/buildingobjects/buildingphysics/wall.py
closes #713 
This should improve readability and give some more feedback to the user if a retrofit was performed or not (e.g. in case of "too modern walls" with already good u values).
> refactor retrofit wall function

- .github/workflows/python-package.yml
- README.md
closes #731 by removing the Webtool and it's URL from README.md
> remove not existing webtool from readme

- teaser/data/output/reports/model_report.py
Minor improvements to make the model export a bit more robust
If no `height_of_floors` is given (only mandatory for archetypes), a default value of 3 m is used. If this is the case this is also stated in the model report (see attached screenshot)
> Improve model report

- teaser/data/output/reports/model_report.py
Small fix. The prior code lead depending on the structure of the model to wrong assignments of the orientation of the outer wall areas.
> fix outer area calculation for visualization

- teaser/data/output/modelicatemplate/AixLib/AixLib_Multizone
This was somehow removed in the latest merges and caused the bim2sim pipelines to fail.
> Add post processing block to multizone template again

- teaser/data/input/teaserjson_input.py
This is regarding issue #777 
@DaJansenGit hope this is fine
> Issue777 buildingahu input json

- teaser/__init__.py
- teaser/logic/retrofit.py
- teaser/project.py
- tests/test_partial_retrofit.py
@Nico-yf  @larissakuehn 
Based on the scripts you provided me to retrofit single building elements, I implemented this feature for TEASER. Could one or both of you check if the functions work for you in your lib and review the code? Be aware that you have to switch to the latest TEASER version to check.
Regarding naming of the buildings, I followed your approach,  @Nico-yf. We could add an option so that users may define the names based on a callable? E.g. :
```
def get_retrofit_name(element_retrofit_stats: dict):
retrofit_name = ''.join(
f"{element[:2]}{retrofit_dict[retrofit_option]}"
for element, retrofit_option in element_retrofit_stats.items()
)
return retrofit_name
```
> 774 retrofit combos

- docs/jupyter_notebooks/e3_export_ibpsa_models.ipynb
- docs/source/examples/e3_export_ibpsa_models.md
- teaser/data/output/modelicatemplate/IBPSA/IBPSA_FourElements
- teaser/data/output/modelicatemplate/IBPSA/IBPSA_OneElement
- teaser/data/output/modelicatemplate/IBPSA/IBPSA_ThreeElements
- teaser/data/output/modelicatemplate/IBPSA/IBPSA_TwoElements
- teaser/examples/e3_export_ibpsa_models.py
- teaser/logic/buildingobjects/calculation/ibpsa.py
lat is not longer supported in latest IBPSA libraries, e.g. AixLib, IBPSA or IDEAS. Also, stated versions are not correct. Closes #755
> fixes to let ipbsa example run

- teaser/data/output/besmod_output.py
- tests/test_besmod_output.py
> 795 besmod examples without hydraulic

- teaser/__init__.py
- teaser/logic/buildingobjects/building.py
- tests/test_data.py
> fix default parameters for calc_building_parameter class

- teaser/logic/buildingobjects/calculation/four_element.py
- teaser/logic/buildingobjects/calculation/one_element.py
- teaser/logic/buildingobjects/calculation/three_element.py
- teaser/logic/buildingobjects/calculation/two_element.py
original changes were not correct. For two_element model a dummy value already existed and was set to 9999.0. I removed the duplicated dummy value and added 9999.0 instead of zero to the other models.
> correct shading_max_irr values

- tests/test_data.py
This should solve a current problem where python 3.12. pipelines fail due to some changes in python 3.12. handling floating point calculations.
> update calculations from round() to approx

- teaser/logic/buildingobjects/calculation/four_element.py
- teaser/logic/buildingobjects/calculation/one_element.py
- teaser/logic/buildingobjects/calculation/three_element.py
I accidentally re-added a bug that was previously solved through the merge of the five-element branch. This solves the bug (again)
closes #803
> fig bug that was reintroduced through previous merge
