teaser/data/input/citygml_input.py, teaser/logic/archetypebuildings/bmvbs/office.py, teaser/logic/archetypebuildings/bmvbs/singlefamilydwelling.py, teaser/logic/buildingobjects/building.py, teaser/logic/buildingobjects/thermalzone.py, teaser/logic/simulation/aixlib.py, teaser/project.py
should improve import functionality of citygml
=> Issue245 city gm limprov

teaser/gui/mainui.py
=> Issue283 empty project

teaser/data/output/aixlib_output.py, teaser/data/output/annex60_output.py
=> switches from MSL 3.2.1 to 3.2.2

doc/teaser.Examples.rst
This should solve the Documentation type #295
=> #295 changed the typo in the documentation example

doc/teaser.Examples.rst, teaser/logic/buildingobjects/thermalzone.py
Merge PR #300 first and then this should solve the Bug #294
=> Issue294 bug calc three element

teaser/gui/controller/controller.py
This time it should be the right branch.
=> #314 bug fix, changed position to id

teaser/gui/mainui.py
#285 stays open as there might be more work to do
=> Deletes ':' throughout the GUI to have a unified design

.travis.yml
=> #356 added travis file to test agains 2.7, 3.4, 3.5

teaser/data/output/modelicatemplate/AixLib/AixLib_ThermalZoneRecord, teaser/logic/buildingobjects/boundaryconditions/boundaryconditions.py, tests/test_data.py
This should solve the problem that the infiltration rate is not used in the export. 
See #193
=> Issue193 infiltration rate

teaser/data/input/inputdata/MaterialTemplates.xml
adds solar absorp to material #344
=> add solar absorption

teaser/data/output/annex60_output.py
@MichaMans could you check this pls?
=> bugfix for annex model export

teaser/gui/controller/controller.py, teaser/gui/mainui.py, teaser/logic/buildingobjects/thermalzone.py, teaser/project.py
revised the gui to work under 0.5
=> Issue368 gui

teaser/data/input/boundcond_input.py, teaser/data/input/inputdata/UseConditions.xml, teaser/data/output/boundcond_output.py, teaser/logic/buildingobjects/boundaryconditions/boundaryconditions.py
=> add attributes to xml and to loader and saver, #388

teaser/logic/buildingobjects/buildingphysics/wall.py, tests/test_data.py
Add further retrofit years to wall elements #391
=> Add retrofit options between 1977 and 1994 to walls in wall.py #391

teaser/examples/verification/vdi6007_testcases/vdi6007_case11.py, teaser/examples/verification/vdi6007_testcases/vdi6007_case12.py, teaser/logic/simulation/VDI_6007/eqAirTemp.py, teaser/logic/simulation/VDI_6007/equal_air_temperature.py, teaser/logic/simulation/VDI_6007/low_order_VDI.py, teaser/logic/simulation/VDI_6007/weather.py, tests/test_data.py
Set new reference values to VDI 6007 test cases
=> Issue297 vdi core test ref

teaser/logic/archetypebuildings/bmvbs/custom/institute.py, teaser/logic/archetypebuildings/bmvbs/custom/institute4.py, teaser/logic/archetypebuildings/bmvbs/custom/institute8.py, teaser/logic/archetypebuildings/bmvbs/office.py
this adds ordereddict for `zone_area_factors` to have the same order in modelica export of thermal zones
=> add ordered dict

teaser/logic/buildingobjects/calculation/four_element.py
=> fixes bug in line 1163

teaser/logic/buildingobjects/calculation/four_element.py
=> cleans up code

teaser/examples/e6_generate_building.py
=> Fixes bug in in_wall_dict

teaser/logic/buildingobjects/calculation/annex60.py
=> changes used version of Annex60

README.md, doc/development.rst, doc/index.rst, teaser/data/output/aixlib_output.py, teaser/data/output/ibpsa_output.py, teaser/data/output/modelicatemplate/IBPSA/IBPSA_FourElements, teaser/data/output/modelicatemplate/IBPSA/IBPSA_OneElement, teaser/data/output/modelicatemplate/IBPSA/IBPSA_ThreeElements, teaser/data/output/modelicatemplate/IBPSA/IBPSA_TwoElements, teaser/examples/e3_export_ibpsa_models.py, teaser/logic/buildingobjects/calculation/aixlib.py, teaser/logic/buildingobjects/calculation/ibpsa.py, teaser/project.py, tests/test_data.py
This solves #440 and also adds development section to doc
=> Issue440 ibpsa

doc/development.rst, doc/faq.rst, doc/index.rst
Adds a FAQ section to the documentation and sovles #442
=> added faq section

.travis.yml
This closes #454
If everything works fine, after that PR, every new tag is automatically shipped to PyPi. It gets only active for tags, not on PRs, and only for `master`.
However, I couldn't test it, therefore it needs to be on the `master`.
=> Adds part for Travis CD to PyPi to yml file

teaser/project.py
=> Issue 484 path save project

teaser/project.py
=> Issue475 typo

teaser/logic/archetypebuildings/bmvbs/office.py, teaser/logic/archetypebuildings/bmvbs/singlefamilydwelling.py, teaser/logic/archetypebuildings/tabula/de/singlefamilyhouse.py, teaser/logic/archetypebuildings/urbanrenet/est1a.py
=> Issue482 archetype

teaser/logic/simulation/modelicainfo.py
=> #511 added Cvode to supported solvers and set it to default

teaser/logic/archetypebuildings/tabula/de/singlefamilyhouse.py
=> #523 added number of persons and machins calculation

doc/Literatur.bib, doc/archetypes.rst, doc/teaser.Logic.ArchetypeBuildings.rst, doc/teaser.Logic.ArchetypeBuildings.tabula.rst
This should create new docs and Literature is shown again
=> added new docu

teaser/data/input/inputdata/UseConditions.xml, teaser/logic/buildingobjects/calculation/aixlib.py
Adding profiles for retail UseConditions and corrected the illuminance values for the retail zones.
=> Issue544 retail profiles

teaser/logic/buildingobjects/calculation/aixlib.py
I left the original code as comments in order to make changes more comprehensibly.
=> Proper initialization of time_line attribute in aixlib.py

teaser/data/input/inputdata/UseConditions.xml
Values for maintained illuminance boundary condition in UseConditions.xml have been changed according to DIN V18599-1.
=> Adjustment of maintained illuminance condition according to DIN V18599-1

.gitlab-ci.yml
As of today we are able to use gitlab enterprise features. To test this i'll want to integrate the gitlab ci pipeline to this project.
=> Integration gitlab ci

teaser/data/output/modelicatemplate/conversion
should solve bug reported in #561
=> treat 360 as 0 degree

.gitlab-ci.yml, .travis.yml, teaser/logic/buildingobjects/boundaryconditions/boundaryconditions.py, teaser/logic/buildingobjects/calculation/ibpsa.py, tests/test_data.py, tests/test_modelicaversion.py
This is related to #568.
The AixLib version from IBSPA export wasn't up2date so we changed this. Also the docstric for the internal gains by persons was updated.
=> Issue567 specific persons and machines

teaser/data/input/usecond_input.py, teaser/logic/archetypebuildings/bmvbs/custom/institute.py
This solves #602 can you please review this @DaJansenGit :) Thanks!
=> add with ahu statement to import

teaser/logic/buildingobjects/calculation/aixlib.py
=> raise aixlib version to v0.8.3

.travis.yml, README.md, setup.py, teaser/logic/buildingobjects/calculation/aixlib.py, teaser/logic/buildingobjects/calculation/ibpsa.py
As described in #627 I made a quite stupid mistake :) this fixes the mistake.
=> increase version numbers of modelica libraries, TEASER, only deploy once

teaser/logic/buildingobjects/buildingphysics/buildingelement.py
=> #635 should revise the setters

teaser/data/input/inputdata/MaterialTemplates.json, teaser/examples/e9_building_data_import_from_excel.py, teaser/logic/buildingobjects/buildingphysics/buildingelement.py, teaser/logic/buildingobjects/buildingphysics/wall.py, teaser/logic/buildingobjects/buildingsystems/buildingahu.py, teaser/logic/buildingobjects/calculation/four_element.py, teaser/logic/buildingobjects/calculation/one_element.py, teaser/logic/buildingobjects/calculation/three_element.py, teaser/logic/buildingobjects/calculation/two_element.py, teaser/logic/buildingobjects/useconditions.py
#640 
Typos and some changes at the excel import example script.
=> Issue640 typos and more

setup.py
=> Add missing file to setup

teaser/data/output/aixlib_output.py, teaser/logic/utilities.py
=> solve export problem

.github/workflows/python-package.yml
This action should autodeploy teaser to pypi if a new tag is created. @MartinRaetz could you approve?
=> Pypi actions

teaser/logic/buildingobjects/thermalzone.py, tests/test_data.py
=> fix: integrate unique zone names to solve #705

README.md
> Thank you for making a Pull Request to TEASER!
> Please consider these points before submitting:
> - Mention the issue that this Pull Request intends to solve, and briefly describe what the main changes are.
> If you know someone who could review your code, please use the *Reviewer* function on the right to ask for a review and also assign the PR to them. If not, no worries, we will find someone for you.
> Thanks again for your PR! You can delete these first lines before submitting your PR.
=> Remove session id from logo source

teaser/logic/buildingobjects/buildingphysics/outerwall.py, teaser/project.py
=> chore: add additional documentation for area and merge_windows_calc

teaser/examples/e8_change_boundary_conditions.py
same as #712 but for development
=> fix typo in e8, bug is already solved in master

teaser/data/output/modelicatemplate/AixLib/AixLib_ThermalZoneRecord_FourElement, teaser/data/output/modelicatemplate/AixLib/AixLib_ThermalZoneRecord_OneElement, teaser/data/output/modelicatemplate/AixLib/AixLib_ThermalZoneRecord_ThreeElement, teaser/data/output/modelicatemplate/AixLib/AixLib_ThermalZoneRecord_TwoElement, teaser/logic/buildingobjects/calculation/aixlib.py, teaser/logic/buildingobjects/calculation/four_element.py, teaser/logic/buildingobjects/calculation/one_element.py, teaser/logic/buildingobjects/calculation/three_element.py, teaser/logic/buildingobjects/calculation/two_element.py
closes #707 
should be merged together with [this AixLib PR](https://github.com/RWTH-EBC/AixLib/pull/1328)
=> integrate parameters for dynamic heat load calc in modelica

teaser/data/output/modelicatemplate/AixLib/AixLib_Multizone
=> add missing connection for multizone post process

teaser/logic/buildingobjects/calculation/aixlib.py
=> chore: bump aixlib version

teaser/data/output/aixlib_output.py, teaser/data/output/modelicatemplate/AixLib/AixLib_Multizone, teaser/examples/e2_export_aixlib_models.py, teaser/project.py
closes #748. Relevant information can be found in the issue!
=> add __Dymola_selection implementation

teaser/logic/buildingobjects/calculation/aixlib.py, teaser/logic/buildingobjects/calculation/ibpsa.py
=> fix freq warning

teaser/data/dataclass.py
=> Issue750 read only in dataclass

teaser/logic/buildingobjects/building.py
=> fix bug with `with_ahu` setter method

teaser/data/input/teaserjson_input.py
This brings the changes from external PR #778 from @PGorzalka into development.
=> Issue777 buildingahu input json

teaser/logic/buildingobjects/calculation/aixlib.py
@Dawac Can you review this version update PR?
Closes #780
=> Update AixLib version

teaser/logic/buildingobjects/useconditions.py
=> update data source docs for maintained_illuminance

teaser/examples/e6_generate_building.py, tests/test_teaser_json.py
This add some tests if the save and load functions work properly
=> add tests for save and load as json functions

teaser/__init__.py, teaser/logic/buildingobjects/calculation/four_element.py, teaser/logic/buildingobjects/calculation/one_element.py, teaser/logic/buildingobjects/calculation/three_element.py, teaser/logic/buildingobjects/calculation/two_element.py
=> fix size of shading_max_irr

teaser/__init__.py, teaser/data/output/aixlib_output.py, teaser/data/output/besmod_output.py, teaser/data/output/ibpsa_output.py, teaser/data/output/modelica_output.py
=> Fix custom paths

teaser/__init__.py, teaser/logic/buildingobjects/calculation/four_element.py, teaser/logic/buildingobjects/calculation/one_element.py, teaser/logic/buildingobjects/calculation/three_element.py, teaser/logic/buildingobjects/calculation/two_element.py, teaser/project.py
=> 816 minor bug fixes

teaser/logic/buildingobjects/useconditions.py, tests/test_useconditions.py
> Thank you for making a Pull Request to TEASER!
> Please consider these points before submitting:
> - Mention the issue that this Pull Request intends to solve, and briefly describe what the main changes are.
> If you know someone who could review your code, please use the *Reviewer* function on the right to ask for a review and also assign the PR to them. If not, no worries, we will find someone for you.
> Thanks again for your PR! You can delete these first lines before submitting your PR.
=> Delete value error #823
